from libqtile import bar, widget

from assets.constants import Colours, FONT_TYPE
from scripts.utils import get_audio_output_device


top_bar = bar.Bar(
    [
        widget.Spacer(
            length=12,
            background=Colours.HIGHLIGHT,
        ),
        widget.Image(
            filename="~/.config/qtile/assets/graphics/logo.png",
            background=Colours.HIGHLIGHT,
            padding=16,
        ),
        widget.Image(
            filename="~/.config/qtile/assets/graphics/bar_shadow_divider_up.svg",
            background=Colours.DARKER_BACKGROUND,
        ),
        widget.GroupBox(
            fontsize=18,
            borderwidth=3,
            highlight_method="border",
            active=Colours.GOLD,
            block_highlight_text_color=Colours.WHITE,
            inactive=Colours.GREY,
            background=Colours.DARKER_BACKGROUND,
            rounded=True,
            this_current_screen_border=Colours.HIGHLIGHT,
            this_screen_border=Colours.BACKGROUND,
            other_current_screen_border=Colours.BACKGROUND,
            other_screen_border=Colours.BACKGROUND,
            urgent_border=Colours.BACKGROUND,
            disable_drag=True,
            font=FONT_TYPE,
        ),
        widget.Image(
            filename="~/.config/qtile/assets/graphics/bar_shadow_divider_down.svg",
            background=Colours.DARKER_BACKGROUND,
        ),
        widget.Image(
            filename="~/.config/qtile/assets/graphics/layout.png",
            background=Colours.BACKGROUND,
        ),
        widget.CurrentLayout(
            background=Colours.BACKGROUND,
            foreground=Colours.WHITE,
            fmt="{}",
            font=FONT_TYPE,
            fontsize=13,
        ),
        widget.Image(
            filename="~/.config/qtile/assets/graphics/bar_semi_circle_right.svg",
            background=Colours.DARKER_BACKGROUND,
        ),
        widget.WindowName(
            background=Colours.DARKER_BACKGROUND,
            format="{name}",
            font=FONT_TYPE,
            foreground=Colours.WHITE,
            empty_group_string="Desktop",
            fontsize=13,
        ),
        widget.Image(
            background=Colours.DARKER_BACKGROUND,
            filename="~/.config/qtile/assets/graphics/bar_semi_circle_left.svg",
        ),
        widget.Image(
            filename="~/.config/qtile/assets/graphics/internet.png",
            background=Colours.BACKGROUND,
            margin_y=6,
            padding=8,
        ),
        widget.WlanIw(
            format="{essid} {percent:2.0%}",
            font=FONT_TYPE,
            fontsize=13,
            interface="wlp2s0",
            background=Colours.BACKGROUND,
        ),
        widget.Image(
            filename="~/.config/qtile/assets/graphics/bar_divider_5.svg",
            background=Colours.BACKGROUND,
        ),
        widget.Image(
            padding=10,
            margin_y=6,
            filename="~/.config/qtile/assets/graphics/bluetooth.svg",
            background=Colours.BACKGROUND,
        ),
        widget.Bluetooth(
            hci="/org/bluez/hci0",
            experimental=True,
            padding=8,
            fontsize=13,
            background=Colours.BACKGROUND,
        ),
        widget.Image(
            filename="~/.config/qtile/assets/graphics/bar_divider_5.svg",
            background=Colours.BACKGROUND,
        ),
        widget.Image(
            margin_y=2,
            margin_x=2,
            filename="~/.config/qtile/assets/graphics/cpu.png",
            background=Colours.BACKGROUND,
        ),
        widget.CPU(
            format="{load_percent}%",
            foreground=Colours.WHITE,
            background=Colours.BACKGROUND,
            min_chars=6,
            fontsize=13,
            max_chars=6,
        ),
        widget.Image(
            filename="~/.config/qtile/assets/graphics/bar_divider_5.svg",
            background=Colours.BACKGROUND,
        ),
        widget.Image(
            margin_y=4,
            margin_x=2,
            filename="~/.config/qtile/assets/graphics/ram.png",
            background=Colours.BACKGROUND,
        ),
        widget.Memory(
            background=Colours.BACKGROUND,
            format="{MemUsed: .0f}{mm}",
            foreground=Colours.WHITE,
            font=FONT_TYPE,
            fontsize=13,
            update_interval=5,
        ),
        widget.Image(
            filename="~/.config/qtile/assets/graphics/bar_divider_5.svg",
            background=Colours.BACKGROUND,
        ),
        widget.BatteryIcon(
            battery="BAT0",
            theme_path="~/.config/qtile/assets/graphics/battery_theme/",
            background=Colours.BACKGROUND,
            scale=1,
        ),
        widget.Battery(
            battery="BAT0",
            font=FONT_TYPE,
            background=Colours.BACKGROUND,
            foreground=Colours.WHITE,
            format="{percent:2.0%}",
            fontsize=13,
            low_foreground=Colours.WARNING,
            low_percentage=0.2,
        ),
        widget.Image(
            filename="~/.config/qtile/assets/graphics/bar_divider_5.svg",
            background=Colours.BACKGROUND,
        ),
        widget.GenPollCommand(
            cmd="asusctl profile -p | grep 'Active profile' | awk '{print $NF}'",
            update_interval=5,
            fmt="⚡ {}",
            shell=True,
            background=Colours.BACKGROUND,
        ),
        widget.Image(
            filename="~/.config/qtile/assets/graphics/bar_divider_5.svg",
            background=Colours.BACKGROUND,
        ),
        widget.Volume(
            font=FONT_TYPE,
            background=Colours.BACKGROUND,
            foreground=Colours.WHITE,
            fontsize=18,
            emoji=True,
            padding=10,
        ),
        widget.Spacer(
            length=-5,
            background=Colours.BACKGROUND,
        ),
        widget.GenPollText(
            update_interval=2,
            func=get_audio_output_device,
            font=FONT_TYPE,
            background=Colours.BACKGROUND,
            foreground=Colours.WHITE,
            fontsize=13,
        ),
        widget.Image(
            filename="~/.config/qtile/assets/graphics/bar_divider_6.svg",
            background=Colours.BACKGROUND,
        ),
        widget.Clock(
            background=Colours.HIGHLIGHT,
            foreground=Colours.BLACK,
            font=FONT_TYPE,
            fontsize=18,
        ),
        widget.Spacer(
            length=8,
            background=Colours.HIGHLIGHT,
        ),
    ],
    size=32,
    border_width=[0, 0, 0, 0],
    margin=[10, 10, 0, 10],
)
